import { StaffMember, KpiCriterion, KpiIncident, UserAccount, SchoolUiSettings } from './types';

export const SCHOOL_CONFIG = {
  fullName: 'TRƯỜNG THPT PHƯƠNG XÁ',
  shortName: 'THPT PHƯƠNG XÁ',
  normalName: 'Trường THPT Phương Xá',
  department: 'SỞ GD&ĐT PHÚ THỌ',
  subLocation: 'Phương Xá, Cẩm Khê, Phú Thọ',
  code: '010203 - Phú Thọ',
  email: 'c3phuongxa.phutho@moet.edu.vn',
  phone: '0210.387x.xxx',
};

export const DEFAULT_SCHOOL_UI_SETTINGS: SchoolUiSettings = {
  id: 'active_settings',
  school_name: 'TRƯỜNG THPT PHƯƠNG XÁ',
  department_name: 'SỞ GD&ĐT PHÚ THỌ',
  system_name: 'HỆ THỐNG QUẢN LÝ KPI & ĐÁNH GIÁ THI ĐUA NỘI BỘ',
  slogan: 'TRI THỨC - NHÂN CÁCH - TƯƠNG LAI',

  logo_url: '',
  school_image_url: '',
  header_background_url: '',

  header_bg_type: 'gradient',
  header_gradient_from: '#1e3a8a',
  header_gradient_to: '#312e81',
  header_bg_opacity: 95,
  header_bg_brightness: 100,
  header_bg_blur: 0,

  primary_color: '#1e3a8a',
  secondary_color: '#0284c7',
  text_color: '#ffffff',
  background_color: '#f8fafc',
  sidebar_color: '#ffffff',
  button_color: '#2563eb',

  header_height: 76,
  logo_size: 44,
  school_image_size: 96,
  school_name_font_size: 18,
  department_font_size: 12,
  slogan_font_size: 12,

  elements_order: [
    'logo',
    'department_name',
    'school_name',
    'system_name',
    'slogan',
    'school_image',
  ],

  show_logo: true,
  show_department_name: true,
  show_school_name: true,
  show_system_name: true,
  show_slogan: true,
  show_school_image: true,
  show_header_background: true,

  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  updated_by: 'BGH',
};


export const CURRENT_SCHOOL_YEAR = '2026 - 2027';
export const CURRENT_SEMESTER: 1 | 2 = 1;
export const CURRENT_MONTH = 9; // September 2026

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'user-bgh',
    username: 'bgh_hieutruong',
    name: 'Thầy Lê Quốc Tuấn',
    role: 'bgh',
    personId: 'bgh-01',
    position: 'Hiệu trưởng',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-gv',
    username: 'gv_nguyenana',
    name: 'Nguyễn Văn A',
    role: 'giaovien',
    personId: 'gv-01',
    position: 'Giáo viên Toán - Tổ trưởng',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-nv',
    username: 'nv_ketoan',
    name: 'Trần Thị Lan',
    role: 'nhanvien',
    personId: 'nv-01',
    position: 'Kế toán trưởng',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  // Ban Giám hiệu (3 CBQL)
  {
    id: 'bgh-01',
    code: 'BGH001',
    name: 'Thầy Lê Quốc Tuấn',
    type: 'bgh',
    employee_type: 'BGH',
    department: 'Ban Giám hiệu',
    departmentId: 'ban-giam-hieu',
    department_id: 'ban-giam-hieu',
    position: 'Hiệu trưởng',
    phone: '0983.123.456',
    email: 'hieutruong.thptphuongxa@edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'bgh-02',
    code: 'BGH002',
    name: 'Cô Đặng Thu Hằng',
    type: 'bgh',
    employee_type: 'BGH',
    department: 'Ban Giám hiệu',
    departmentId: 'ban-giam-hieu',
    department_id: 'ban-giam-hieu',
    position: 'Phó Hiệu trưởng (Chuyên môn)',
    phone: '0912.345.678',
    email: 'hangdt.thptphuongxa@edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'bgh-03',
    code: 'BGH003',
    name: 'Thầy Nguyễn Văn Long',
    type: 'bgh',
    employee_type: 'BGH',
    department: 'Ban Giám hiệu',
    departmentId: 'ban-giam-hieu',
    department_id: 'ban-giam-hieu',
    position: 'Phó Hiệu trưởng (Cơ sở vật chất - Nề nếp)',
    phone: '0977.888.999',
    email: 'longnv.thptphuongxa@edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },

  // Giáo viên các tổ chuyên môn (12 Giáo viên)
  {
    id: 'gv-01',
    code: 'GV001',
    name: 'Nguyễn Văn A',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Toán - Lí - Tin',
    departmentId: 'to-toan-li-tin',
    department_id: 'to-toan-li-tin',
    position: 'Tổ trưởng Chuyên môn',
    subject: 'Toán học',
    classAssigned: '12A1',
    phone: '0901.111.222',
    email: 'anv.toan@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-02',
    code: 'GV002',
    name: 'Trần Thị B',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Văn - Ngoại ngữ',
    departmentId: 'to-van-nn',
    department_id: 'to-van-nn',
    position: 'Tổ trưởng Chuyên môn',
    subject: 'Ngữ văn',
    classAssigned: '11B2',
    phone: '0902.333.444',
    email: 'btt.van@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-03',
    code: 'GV003',
    name: 'Lê Văn C',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Văn - Ngoại ngữ',
    departmentId: 'to-van-nn',
    department_id: 'to-van-nn',
    position: 'Tổ phó Chuyên môn',
    subject: 'Tiếng Anh',
    classAssigned: '10C1',
    phone: '0903.555.666',
    email: 'clv.anh@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-04',
    code: 'GV004',
    name: 'Phạm Thị D',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Toán - Lí - Tin',
    departmentId: 'to-toan-li-tin',
    department_id: 'to-toan-li-tin',
    position: 'Tổ phó Chuyên môn',
    subject: 'Vật lý',
    classAssigned: '12A3',
    phone: '0904.777.888',
    email: 'dpt.ly@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-05',
    code: 'GV005',
    name: 'Hoàng Văn E',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Hóa - Sinh - CN',
    departmentId: 'to-hoa-sinh-cn',
    department_id: 'to-hoa-sinh-cn',
    position: 'Tổ trưởng Chuyên môn',
    subject: 'Sinh học',
    classAssigned: '10A4',
    phone: '0905.999.000',
    email: 'ehv.sinh@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-06',
    code: 'GV006',
    name: 'Vũ Thị Minh Trang',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Hóa - Sinh - CN',
    departmentId: 'to-hoa-sinh-cn',
    department_id: 'to-hoa-sinh-cn',
    position: 'Bí thư Đoàn trường',
    subject: 'Hóa học',
    classAssigned: '11A2',
    phone: '0913.222.333',
    email: 'trangvtm.hoa@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-07',
    code: 'GV007',
    name: 'Đỗ Phương Tuấn',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Hóa - Sinh - CN',
    departmentId: 'to-hoa-sinh-cn',
    department_id: 'to-hoa-sinh-cn',
    position: 'Giáo viên Giảng dạy',
    subject: 'Hóa học',
    classAssigned: '11B1',
    phone: '0914.444.555',
    email: 'tuandp.hoa@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-08',
    code: 'GV008',
    name: 'Bùi Ngọc Lan',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Sử - Địa - KT&PL - TD - QPAN',
    departmentId: 'to-su-dia',
    department_id: 'to-su-dia',
    position: 'Tổ trưởng Chuyên môn',
    subject: 'Lịch sử',
    classAssigned: '12C2',
    phone: '0915.666.777',
    email: 'lanbn.su@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-09',
    code: 'GV009',
    name: 'Nguyễn Tiến Dũng',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Sử - Địa - KT&PL - TD - QPAN',
    departmentId: 'to-su-dia',
    department_id: 'to-su-dia',
    position: 'Giáo viên Giảng dạy',
    subject: 'Địa lý',
    classAssigned: '10B3',
    phone: '0916.888.999',
    email: 'dungnt.dia@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-10',
    code: 'GV010',
    name: 'Phạm Hoài Phương',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Sử - Địa - KT&PL - TD - QPAN',
    departmentId: 'to-su-dia',
    department_id: 'to-su-dia',
    position: 'Tổ phó Chuyên môn',
    subject: 'Giáo dục Quốc phòng',
    classAssigned: '12A2',
    phone: '0917.111.000',
    email: 'phuongph.gdqp@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-11',
    code: 'GV011',
    name: 'Nguyễn Thị Hải Yến',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Hóa - Sinh - CN',
    departmentId: 'to-hoa-sinh-cn',
    department_id: 'to-hoa-sinh-cn',
    position: 'Tổ phó Chuyên môn',
    subject: 'Công nghệ',
    classAssigned: '10A2',
    phone: '0918.222.111',
    email: 'yennth.cn@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'gv-12',
    code: 'GV012',
    name: 'Trần Quốc Bảo',
    type: 'giaovien',
    employee_type: 'GIAO_VIEN',
    department: 'Tổ Sử - Địa - KT&PL - TD - QPAN',
    departmentId: 'to-su-dia',
    department_id: 'to-su-dia',
    position: 'Giáo viên Thể dục',
    subject: 'Giáo dục Thể chất',
    classAssigned: '11C1',
    phone: '0919.333.222',
    email: 'baotq.td@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },

  // Nhân viên Tổ Văn phòng (Đầy đủ nhân sự theo 8 vị trí việc làm chuẩn hóa)
  {
    id: 'nv-ttvp-01',
    code: 'TTVP01',
    name: 'Hoàng Mỹ Hạnh',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Tổ trưởng Tổ Văn phòng',
    phone: '0934.888.999',
    email: 'hanhhm.vanphong@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-01',
    code: 'NV001',
    name: 'Trần Thị Lan',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Kế toán trưởng',
    phone: '0934.111.222',
    email: 'lantt.ketoan@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-02',
    code: 'NV002',
    name: 'Nguyễn Văn Tuấn',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Kế toán',
    phone: '0934.333.444',
    email: 'tuannv.ketoan@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-03',
    code: 'NV003',
    name: 'Hoàng Thị Mai',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Thủ quỹ',
    phone: '0935.111.888',
    email: 'maiht.thuquy@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-04',
    code: 'NV004',
    name: 'Phạm Thu Hương',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Văn thư - Lưu trữ',
    phone: '0935.333.444',
    email: 'huongpt.vanthu@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-05',
    code: 'NV005',
    name: 'Vũ Thị Hồng',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Văn thư',
    phone: '0935.555.777',
    email: 'hongvt.vanthu@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-06',
    code: 'NV006',
    name: 'Nguyễn Hải Đăng',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Y tế học đường',
    phone: '0936.555.666',
    email: 'dangnh.yte@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-07',
    code: 'NV007',
    name: 'Đỗ Văn Hùng',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Bảo vệ trường',
    phone: '0938.111.333',
    email: 'hungdv.baove@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-08',
    code: 'NV008',
    name: 'Trần Văn Cường',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Bảo vệ',
    phone: '0938.222.444',
    email: 'cuongtv.baove@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-09',
    code: 'NV009',
    name: 'Nguyễn Thị Thơm',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Phục vụ/Vệ sinh',
    phone: '0939.888.999',
    email: 'thomnt.phucvu@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-10',
    code: 'NV010',
    name: 'Lê Thị Tuyết',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Thư viện',
    phone: '0937.777.888',
    email: 'tuyetlt.thuvien@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-11',
    code: 'NV011',
    name: 'Ngô Văn Minh',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Thiết bị',
    phone: '0936.888.111',
    email: 'minhnv.thietbi@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
  {
    id: 'nv-12',
    code: 'NV012',
    name: 'Đặng Hồng Phong',
    type: 'nhanvien',
    employee_type: 'NHAN_VIEN',
    department: 'Tổ Văn phòng',
    departmentId: 'to-van-phong',
    department_id: 'to-van-phong',
    position: 'Nhân viên Thiết bị',
    phone: '0936.999.222',
    email: 'phongdh.thietbi@thptphuongxa.edu.vn',
    status: 'Đang công tác',
    is_active: true,
    baseScore: 100,
  },
];

export const INITIAL_CRITERIA: KpiCriterion[] = [
  // Tiêu chí nề nếp & vi phạm
  {
    id: 'crit-01',
    code: 'VP01',
    group: 'Nề nếp kỷ cương',
    name: 'Không đeo thẻ công chức / sai trang phục quy định',
    targetRole: 'all',
    type: 'minus',
    points: 2,
    description: 'Vi phạm quy định về trang phục sư phạm, không đeo bảng tên/thẻ công chức khi làm nhiệm vụ.',
    status: 'active',
  },
  {
    id: 'crit-02',
    code: 'VP02',
    group: 'Nề nếp kỷ cương',
    name: 'Vào muộn, ra sớm hoặc bỏ tiết giảng dạy / phiên trực',
    targetRole: 'all',
    type: 'minus',
    points: 5,
    description: 'Đến trường muộn hơn 15 phút hoặc kết thúc tiết trước hiệu lệnh mà không có lý do chính đáng.',
    status: 'active',
  },
  {
    id: 'crit-03',
    code: 'VP03',
    group: 'Hồ sơ chuyên môn',
    name: 'Nộp chậm giáo án, chậm vào sổ điểm, chậm báo cáo tiến độ',
    targetRole: 'giaovien',
    type: 'minus',
    points: 4,
    description: 'Quá hạn nộp giáo án kiểm tra hoặc chậm cập nhật điểm số trên hệ thống cơ sở dữ liệu ngành.',
    status: 'active',
  },
  {
    id: 'crit-04',
    code: 'VP04',
    group: 'Kỳ thi & Đánh giá',
    name: 'Vi phạm quy chế coi thi, chấm thi hoặc nhập sai sót kết quả',
    targetRole: 'giaovien',
    type: 'minus',
    points: 10,
    description: 'Không tuân thủ quy trình bảo mật đề thi hoặc sai lệch điểm tổng kết của học sinh.',
    status: 'active',
  },

  // Tiêu chí chuyên môn tích cực
  {
    id: 'crit-05',
    code: 'VP03_PLUS',
    group: 'Chuyên môn sư phạm',
    name: 'Hoàn thành xuất sắc nhiệm vụ chuyên môn và hội đồng trường',
    targetRole: 'giaovien',
    type: 'plus',
    points: 5,
    description: 'Thực hiện vượt chỉ tiêu giờ dạy, hồ sơ giáo án xếp loại tốt qua kiểm tra định kỳ.',
    status: 'active',
  },
  {
    id: 'crit-06',
    code: 'CM01',
    group: 'Chuyên môn sư phạm',
    name: 'Thực hiện tiết thao giảng / chuyên đề đổi mới phương pháp cấp trường',
    targetRole: 'giaovien',
    type: 'plus',
    points: 6,
    description: 'Tổ chức tiết dạy mẫu có ứng dụng CNTT, STEM, AI hoặc phương pháp dạy học tích cực.',
    status: 'active',
  },
  {
    id: 'crit-07',
    code: 'CM02',
    group: 'Chuyên môn sư phạm',
    name: 'Đạt danh hiệu Giáo viên dạy giỏi cấp trường / cấp Tỉnh',
    targetRole: 'giaovien',
    type: 'plus',
    points: 12,
    description: 'Được công nhận giáo viên dạy giỏi trong kỳ thi giáo viên dạy giỏi các cấp.',
    status: 'active',
  },
  {
    id: 'crit-08',
    code: 'CM03',
    group: 'Bồi dưỡng học sinh',
    name: 'Bồi dưỡng học sinh đạt giải Học sinh giỏi cấp Huyện / Tỉnh',
    targetRole: 'giaovien',
    type: 'plus',
    points: 15,
    description: 'Đội tuyển do giáo viên trực tiếp phụ trách bồi dưỡng có học sinh đạt giải chính thức.',
    status: 'active',
  },
  {
    id: 'crit-09',
    code: 'CM04',
    group: 'Nghiên cứu khoa học',
    name: 'Sáng kiến kinh nghiệm / Đề tài NCKH được xếp loại cấp Sở',
    targetRole: 'all',
    type: 'plus',
    points: 10,
    description: 'Sáng kiến kinh nghiệm được Hội đồng khoa học công nhận có hiệu quả áp dụng thực tiễn.',
    status: 'active',
  },

  // Tiêu chí công tác chủ nhiệm
  {
    id: 'crit-10',
    code: 'TC01',
    group: 'Công tác Chủ nhiệm',
    name: 'Lớp chủ nhiệm dẫn đầu thi đua tuần / tháng không vi phạm',
    targetRole: 'giaovien',
    type: 'plus',
    points: 5,
    description: 'Tập thể lớp chủ nhiệm đạt điểm thi đua cao nhất khối, duy trì sĩ số 100%.',
    status: 'active',
  },
  {
    id: 'crit-11',
    code: 'TC02',
    group: 'Công tác Chủ nhiệm',
    name: 'Lớp chủ nhiệm có học sinh vi phạm kỷ luật nặng hoặc bỏ học',
    targetRole: 'giaovien',
    type: 'minus',
    points: 8,
    description: 'Không nắm bắt kịp thời diễn biến tâm lý học sinh để xảy ra đánh nhau hoặc bỏ học.',
    status: 'active',
  },

  // Tiêu chí Nhân viên
  {
    id: 'crit-12',
    code: 'NV01',
    group: 'Công việc Văn phòng',
    name: 'Hoàn thành công tác tài chính, văn thư, báo cáo vượt hạn mức quy định',
    targetRole: 'nhanvien',
    type: 'plus',
    points: 6,
    description: 'Hồ sơ chứng từ kế toán chuẩn xác, văn bản đến đi được phát hành kịp thời, minh bạch.',
    status: 'active',
  },
  {
    id: 'crit-13',
    code: 'NV02',
    group: 'Học đường & CSVC',
    name: 'Bảo đảm an toàn vệ sinh trường học, y tế, thiết bị phòng học',
    targetRole: 'nhanvien',
    type: 'plus',
    points: 5,
    description: 'Trang thiết bị máy chiếu, phòng thí nghiệm, khuôn viên cây xanh luôn trong tình trạng sẵn sàng tốt.',
    status: 'active',
  },
  {
    id: 'crit-14',
    code: 'NV03',
    group: 'Công việc Văn phòng',
    name: 'Chậm trễ trong chuẩn bị học liệu, thiết bị hoặc thất lạc hồ sơ',
    targetRole: 'nhanvien',
    type: 'minus',
    points: 5,
    description: 'Gây ảnh hưởng đến tiến độ giảng dạy của giáo viên hoặc hoạt động điều hành của nhà trường.',
    status: 'active',
  },

  // Tiêu chí BGH
  {
    id: 'crit-15',
    code: 'BGH01',
    group: 'Lãnh đạo & Quản lý',
    name: 'Chỉ đạo đột phá công tác quản lý chất lượng giáo dục toàn diện',
    targetRole: 'bgh',
    type: 'plus',
    points: 10,
    description: 'Triển khai thành công kế hoạch chuyển đổi số và nâng cao tỷ lệ đỗ tốt nghiệp THPT.',
    status: 'active',
  },
];

export const INITIAL_INCIDENTS: KpiIncident[] = [
  {
    id: 'inc-01',
    personId: 'gv-01',
    personName: 'Nguyễn Văn A',
    personType: 'giaovien',
    department: 'Tổ Toán - Lí - Tin',
    criterionId: 'crit-08',
    criterionCode: 'CM03',
    criterionName: 'Bồi dưỡng học sinh đạt giải Học sinh giỏi cấp Huyện / Tỉnh',
    type: 'plus',
    quantity: 1,
    unitPoints: 15,
    totalPoints: 15,
    date: '2026-09-08',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: '02 học sinh lớp 12A1 đạt giải Nhì cấp Tỉnh môn Toán',
    evidenceRef: 'QĐ-88/QĐ-SGD&ĐT ngày 05/09/2026',
    createdBy: 'Thầy Lê Quốc Tuấn (Hiệu trưởng)',
    createdAt: '2026-09-08T14:30:00Z',
  },
  {
    id: 'inc-02',
    personId: 'gv-01',
    personName: 'Nguyễn Văn A',
    personType: 'giaovien',
    department: 'Tổ Toán - Lí - Tin',
    criterionId: 'crit-06',
    criterionCode: 'CM01',
    criterionName: 'Thực hiện tiết thao giảng / chuyên đề đổi mới phương pháp cấp trường',
    type: 'plus',
    quantity: 1,
    unitPoints: 6,
    totalPoints: 6,
    date: '2026-09-12',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Chuyên đề "Ứng dụng GeoGebra trong khảo sát hàm số"',
    evidenceRef: 'Biên bản sinh hoạt tổ chuyên môn số 03',
    createdBy: 'Cô Đặng Thu Hằng (Phó HT)',
    createdAt: '2026-09-12T16:00:00Z',
  },
  {
    id: 'inc-03',
    personId: 'gv-02',
    personName: 'Trần Thị B',
    personType: 'giaovien',
    department: 'Tổ Văn - Ngoại ngữ',
    criterionId: 'crit-05',
    criterionCode: 'VP03_PLUS',
    criterionName: 'Hoàn thành xuất sắc nhiệm vụ chuyên môn và hội đồng trường',
    type: 'plus',
    quantity: 1,
    unitPoints: 5,
    totalPoints: 5,
    date: '2026-09-10',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Hoàn thiện hồ sơ đổi mới phương pháp dạy học Ngữ văn 11',
    evidenceRef: 'Báo cáo tháng 9 Tổ Ngữ văn',
    createdBy: 'Cô Đặng Thu Hằng (Phó HT)',
    createdAt: '2026-09-10T10:15:00Z',
  },
  {
    id: 'inc-04',
    personId: 'gv-02',
    personName: 'Trần Thị B',
    personType: 'giaovien',
    department: 'Tổ Văn - Ngoại ngữ',
    criterionId: 'crit-01',
    criterionCode: 'VP01',
    criterionName: 'Không đeo thẻ công chức / sai trang phục quy định',
    type: 'minus',
    quantity: 1,
    unitPoints: 2,
    totalPoints: 2,
    date: '2026-09-04',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Quên đeo thẻ trong buổi chào cờ thứ Hai',
    evidenceRef: 'Biên bản nề nếp Đoàn thanh niên',
    createdBy: 'Thầy Nguyễn Văn Long (Phó HT)',
    createdAt: '2026-09-04T08:00:00Z',
  },
  {
    id: 'inc-05',
    personId: 'gv-03',
    personName: 'Lê Văn C',
    personType: 'giaovien',
    department: 'Tổ Văn - Ngoại ngữ',
    criterionId: 'crit-06',
    criterionCode: 'CM01',
    criterionName: 'Thực hiện tiết thao giảng / chuyên đề đổi mới phương pháp cấp trường',
    type: 'plus',
    quantity: 1,
    unitPoints: 6,
    totalPoints: 6,
    date: '2026-09-14',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Tiết dạy kết nối quốc tế trực tuyến lớp 10C1',
    evidenceRef: 'Kế hoạch bài dạy số 14-KHBD',
    createdBy: 'Cô Đặng Thu Hằng (Phó HT)',
    createdAt: '2026-09-14T11:20:00Z',
  },
  {
    id: 'inc-06',
    personId: 'gv-04',
    personName: 'Phạm Thị D',
    personType: 'giaovien',
    department: 'Tổ Toán - Lí - Tin',
    criterionId: 'crit-09',
    criterionCode: 'CM04',
    criterionName: 'Sáng kiến kinh nghiệm / Đề tài NCKH được xếp loại cấp Sở',
    type: 'plus',
    quantity: 1,
    unitPoints: 10,
    totalPoints: 10,
    date: '2026-09-05',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Đề tài thí nghiệm ảo Vật lý THPT xếp loại A cấp Ngành',
    evidenceRef: 'Quyết định công nhận SKKN năm 2026',
    createdBy: 'Thầy Lê Quốc Tuấn (Hiệu trưởng)',
    createdAt: '2026-09-05T09:30:00Z',
  },
  {
    id: 'inc-07',
    personId: 'gv-05',
    personName: 'Hoàng Văn E',
    personType: 'giaovien',
    department: 'Tổ Hóa - Sinh - CN',
    criterionId: 'crit-02',
    criterionCode: 'VP02',
    criterionName: 'Vào muộn, ra sớm hoặc bỏ tiết giảng dạy / phiên trực',
    type: 'minus',
    quantity: 1,
    unitPoints: 5,
    totalPoints: 5,
    date: '2026-09-09',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Vào tiết 1 muộn 20 phút do sự cố giao thông',
    evidenceRef: 'Sổ theo dõi nề nếp trường',
    createdBy: 'Thầy Nguyễn Văn Long (Phó HT)',
    createdAt: '2026-09-09T08:30:00Z',
  },
  {
    id: 'inc-08',
    personId: 'gv-06',
    personName: 'Vũ Thị Minh Trang',
    personType: 'giaovien',
    department: 'Tổ Hóa - Sinh - CN',
    criterionId: 'crit-10',
    criterionCode: 'TC01',
    criterionName: 'Lớp chủ nhiệm dẫn đầu thi đua tuần / tháng không vi phạm',
    type: 'plus',
    quantity: 1,
    unitPoints: 5,
    totalPoints: 5,
    date: '2026-09-11',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Lớp 11A2 đạt giải Nhất tuần lễ văn minh học đường',
    evidenceRef: 'Bảng xếp loại tuần 2 Đoàn trường',
    createdBy: 'Thầy Lê Quốc Tuấn (Hiệu trưởng)',
    createdAt: '2026-09-11T17:00:00Z',
  },
  {
    id: 'inc-09',
    personId: 'nv-01',
    personName: 'Trần Thị Lan',
    personType: 'nhanvien',
    department: 'Tổ Văn phòng',
    criterionId: 'crit-12',
    criterionCode: 'NV01',
    criterionName: 'Hoàn thành công tác tài chính, văn thư, báo cáo vượt hạn mức quy định',
    type: 'plus',
    quantity: 1,
    unitPoints: 6,
    totalPoints: 6,
    date: '2026-09-07',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Quyết toán chế độ phụ cấp thâm niên giáo viên nhanh gọn và chuẩn xác',
    evidenceRef: 'Báo cáo tài chính tháng 9/2026',
    createdBy: 'Thầy Lê Quốc Tuấn (Hiệu trưởng)',
    createdAt: '2026-09-07T15:40:00Z',
  },
  {
    id: 'inc-10',
    personId: 'nv-02',
    personName: 'Phạm Thu Hương',
    personType: 'nhanvien',
    department: 'Tổ Văn phòng',
    criterionId: 'crit-12',
    criterionCode: 'NV01',
    criterionName: 'Hoàn thành công tác tài chính, văn thư, báo cáo vượt hạn mức quy định',
    type: 'plus',
    quantity: 1,
    unitPoints: 6,
    totalPoints: 6,
    date: '2026-09-15',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Chuyển giao và số hóa 100% công văn đến đi của Sở GD&ĐT',
    evidenceRef: 'Sổ theo dõi văn thư điện tử',
    createdBy: 'Thầy Lê Quốc Tuấn (Hiệu trưởng)',
    createdAt: '2026-09-15T11:00:00Z',
  },
  {
    id: 'inc-11',
    personId: 'bgh-01',
    personName: 'Thầy Lê Quốc Tuấn',
    personType: 'bgh',
    department: 'Ban Giám hiệu',
    criterionId: 'crit-15',
    criterionCode: 'BGH01',
    criterionName: 'Chỉ đạo đột phá công tác quản lý chất lượng giáo dục toàn diện',
    type: 'plus',
    quantity: 1,
    unitPoints: 10,
    totalPoints: 10,
    date: '2026-09-03',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Tổ chức thành công Lễ Khai giảng và triển khai chương trình GDPT mới',
    evidenceRef: 'Kế hoạch số 01-KH/THPTSL',
    createdBy: 'Hội đồng Thi đua Khen thưởng',
    createdAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'inc-12',
    personId: 'bgh-02',
    personName: 'Cô Đặng Thu Hằng',
    personType: 'bgh',
    department: 'Ban Giám hiệu',
    criterionId: 'crit-15',
    criterionCode: 'BGH01',
    criterionName: 'Chỉ đạo đột phá công tác quản lý chất lượng giáo dục toàn diện',
    type: 'plus',
    quantity: 1,
    unitPoints: 10,
    totalPoints: 10,
    date: '2026-09-06',
    month: 9,
    semester: 1,
    schoolYear: '2026 - 2027',
    notes: 'Hoàn thiện kế hoạch phân phối chương trình dạy học các tổ chuyên môn',
    evidenceRef: 'Biên bản duyệt kế hoạch giáo dục',
    createdBy: 'Thầy Lê Quốc Tuấn (Hiệu trưởng)',
    createdAt: '2026-09-06T10:00:00Z',
  },
];
